{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nginx.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  deletionTimestamp: '2022-07-07T19:36:55Z'
  resourceVersion: '151676'
  name: nginx-demo
  uid: dc635ef5-c2ac-47fe-9837-238984ff6340
  deletionGracePeriodSeconds: 0
  creationTimestamp: '2022-07-07T19:36:55Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2022-07-07T19:36:55Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/version': {}
            'f:helm.sh/chart': {}
        'f:spec':
          'f:port':
            .: {}
            'f:targetPort': {}
          'f:to':
            'f:kind': {}
            'f:name': {}
            'f:weight': {}
          'f:wildcardPolicy': {}
    - manager: openshift-router
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2022-07-07T19:36:55Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:ingress': {}
      subresource: status
  namespace: demo-nginx
  finalizers:
    - foregroundDeletion
  labels:
    app.kubernetes.io/instance: demo-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cherry-awesome-app
    app.kubernetes.io/version: v1
    helm.sh/chart: nginx-0.1.1
spec:
  host: nginx-demo-demo-nginx.apps-crc.testing
  to:
    kind: Service
    name: cherry-chart
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None


